use Srednja_skola;
insert into Nastavnik values
	(1, 'Rade', 'Petrovic', 'Profesor Matematike i Informatika'),
	(2, 'Jovan', 'Markovic', 'Profesor Srpskog jezika'),
	(3, 'Milan', 'Jovanovic', 'Psiholog'),
	(4, 'Rajko', 'Ivanovic', 'Profesor Fizickog'),
	(5, 'Milan', 'Milanovic', 'Profesor Matematike'),
	(6, 'Slavica', 'Grkavac', 'Profesor Engleskog jezika'),
	(7, 'Dusko', 'Pekovic', 'Profesor Matematike'),
	(8, 'Milan', 'Mladenovic', 'Diplomirani Politikolog'),
	(9, 'Jovana', 'Ilic', 'Istoricarka'),
	(10, 'Marija', 'Andric', 'Fizicarka'),
	(11, 'Svetlana', 'Bojkovic', 'Biolog'),
	(12, 'Nenad', 'Boskovic', 'Profesor Istorije i Geografije'),
	(13, 'Vesna', 'Boskovic', 'Profesor Biologije'),
	(14, 'Milorad', 'Lambeta', 'Akademski Slikar'),
	(15, 'Ivana', 'Petrovic', 'Profesor Srpskog jezika'),
	(16, 'Isidora', 'Petricevic', 'Profesor Francuskog jezika'),
	(17, 'Milena', 'Davidovic', 'Profesor Latinskog'),
	(18, 'Rajko', 'Milentijevic', 'Profesor Fizike i Astronomije'),
	(19, 'Starina', 'Novak', 'Profesor Istorije'),
	(20, 'Strahinja', 'Simovic', 'Profesor Muzickog'),
	(21, 'Natalija', 'Rodic', 'Profesor Hemije'),
	(22, 'Rade', 'Petrovic', 'Profesor Nemackog'),
	(23, 'Helena', 'Djuric', 'Profesor Matematike'),
	(24, 'Dragana', 'Kostic', 'Profesor'),
	(25, 'Rastimir', 'Mihic', 'Profesor umetnosti');

insert into Predmet values
	(1456, 'Matematika 1', 'Skupovi , algebarksi izrazi'),
	(2, 'Matematika 2', 'Kvadratna jednacina, Jednacine viseg reda , Kvadratne nejednacine, funkcije'),
	(3, 'Matematika 3', ' logaritmi, trigonometriske  funkcije, nizov, limesi'),
	(4, 'Matematika 4', 'izvodi, integrali'),
	(4444, 'Matematika izborni', 'izvodi, integrali'),
	(5, 'Srpski jezik 1', 'Padezi Glasovne promene - anticka knjizevnost'),
	(6, 'Srpski jezik 2', 'Padezi Glasovne promene - anticka knjizevnost'),
	(7, 'Srpski jezik 3', 'Padezi Glasovne promene - anticka knjizevnost'),
	(811, 'Srpski jezik 4', 'Padezi Glasovne promene - anticka knjizevnost'),
	(8, 'Srpski jezik izorni', 'Padezi Glasovne promene - anticka knjizevnost'),
	(9, 'Engleski jezik 1', 'Sadasnje vreme'),
	(10, 'Engleski jezik 2', 'Sadasnje vreme'),
	(11, 'Engleski jezik 3', 'Sadasnje vreme'),
	(12, 'Engleski jezik 4', 'Sadasnje vreme'),
	(13, 'Francuski jezik 1', 'Uvod'),
	(14, 'Francuski jezik 2', 'Uvod'),
	(15, 'Francuski jezik 3', 'Uvod'),
	(16, 'Francuski jezik 4', 'Uvod'),
	(17, 'Psihologija 1', 'Uvod'),
	(18, 'Psihologija 2', 'Uvod'),
	(19, 'Psihologija 3', 'Uvod'),
	(20, 'Psihologija 4', 'Uvod'),
	(21, 'Fizicko 1', 'Trcanje'),
	(22, 'Fizicko 2', 'Trcanje'),
	(23, 'Fizicko 3', 'Trcanje'),
	(24, 'Fizicko 4', 'Trcanje'),
	(25, 'Informatika 1', 'Koriscenje racunara'),
	(26, 'Informatika 2', 'Koriscenje racunara'),
	(27, 'Informatika 3', 'Koriscenje racunara'),
	(28, 'Informatika 4', 'Koriscenje racunara'),
	(29, 'UStav', 'Osnovno'),
	(30, 'Istoria 1', 'Kameno doba'),
	(31, 'Istoria 2', 'Nemanjici'),
	(32, 'Istoria 3', 'Turci'),
	(33, 'Istoria 4', 'Veliki ratovi'),
	(34, 'Geografija 1', 'Evropa'),
	(35, 'Geografija 2', 'Amerike'),
	(36, 'Geografija 3', 'Azija i australija i afrika'),
	(37, 'Geografija 4', 'Srbija i region'),
	(38, 'Likovno 1', 'Crtanje mrtve prirode'),
	(39, 'Likovno 2', 'Crtanje  prirode'),
	(40, 'Likovno 3', 'Crtanje portreta'),
	(41, 'Muzicko 1', 'Klasicna muzika'),
	(411, 'Muzicko 2', 'Instrumenti muzika'),
	(42, 'Muzicko 3', 'Srpska muzika'),
	(43, 'Fizika 1', 'Statika'),
	(44, 'Fizika 2', 'Dinamika'),
	(45, 'Fizika 3', 'Kinematika'),
	(46, 'Fizika 4', 'El Energija'),
	(47, 'Biologija 1', 'osnove'),
	(48, 'Biologija 2', 'flora '),
	(49, 'Biologija 3', 'fauna'),
	(50, 'Biologija 4', 'anatomija'),
	(51, 'Hemija 1', 'Osnove'),
	(52, 'Hemija 2', 'KIseline'),
	(53, 'Hemija 3', 'Baze'),
	(54, 'Hemija 4', 'Organska hemija');

insert into Smer values	
	(1, 'Drustveni', 'Vecinski se izucavaju drustvene nauke', NULL),
	(2, 'Jezicki', 'Vecinsk se izucavaju jezic', NULL),
	(3, 'Prirodni', 'Vecinski se izucavaju prirodne nauke', NULL),
	(4, 'Matematicki', 'Vecinski se izucava matematika i informatika', NULL);

